apiVersion: v1
kind: Pod
metadata: 
 name: mynginx-taint-noschedule-test-toleration
 labels:        
    devops: '18' 
    company: talent
    type: apply
spec:
  containers:        
  - name: nginx18   
    image: nginx:1.14.1
    ports:
    - containerPort: 80 
  nodeSelector:
    tier: web
  tolerations:
  - key: "name"
    operator: "Equal"
    value: "devops"
    effect: "NoSchedule"    
