apiVersion: batch/v1
kind: Job
metadata:
  name: kubernetes-job-example-parallel
  labels:
    jobgroup: jobexample
spec:
  completions: 10
  parallelism: 2
  template:
    metadata:
      name: kubejob
      labels:
        jobgroup: jobexample
    spec:
      containers:
      - name: parallel-test
        image: devopscube/kubernetes-job-demo:latest
        args: ["10"]
      restartPolicy: OnFailure
