apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test-nodename
  labels:
    purpose: learning
  namespace: preprod
spec:
  replicas: 1
  selector:
     matchLabels:
       type: create
  template:
    metadata:
      name: httpd
      labels:
        devops: '18'
        company: talent
        type: create
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80
      nodeName: k8-worker1 
