apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test-nodeaffinity-soft
  labels:
    purpose: learning
  namespace: preprod
spec:
  replicas: 4
  selector:
     matchLabels:
       type: create
  template:
    metadata:
      name: httpd
      labels:
        devops: '18'
        company: talent
        type: create
    spec:
      containers:
      - name: httpd
        image: nginx
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: batch
                operator: In
                values:
                - 'tts'
