apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-test
  labels:
    purpose: learning
  namespace: preprod
spec:
  replicas: 6
  selector: 
    devops: '18'
  template:
    metadata:
      name: mynginx2-create
      labels:
        devops: '18'
        company: talent
        type: create
    spec:
      containers:
      - name: nginx18
        image: nginx:1.20.1
        ports:
        - containerPort: 80

