apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test
  labels:
    purpose: learning
  namespace: preprod
spec:
  replicas: 4
  selector:
     matchLabels:
       type: create
  template:
    metadata:
      name: httpd
      labels:
        devops: '18'
        company: talent
        type: create
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
