apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-1
  labels:
    purpose: learning
  namespace: dev
spec:
  replicas: 1
  selector:
     matchLabels:
       type: create
  template:
    metadata:
      name: httpd
      labels:
        devops: '18'
        company: talent
        type: create
    spec:
      containers:
      - name: httpd
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 5Mi
          limits:
            memory: 8Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80    
